---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/mavenn-ansible/target/mavennansible.war"
        dest: "/opt/tomcat/webapps/mavenn-ansible.war"
        remote_src: no
        
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
        


